### ISSUE TITLE
WiredTiger Crashes using Multiple Threads

### ISSUE THREAD

**Issue by c-rotte** [unum-cloud/ucsb#3]
UCSB built against WiredTiger 11.0.1 crashes when multiple threads are invoked.

Exemplary workload:
```
{
        "name": "Test",
        "records_count": 200000000,
        "operations_count": 200000000,
        "upsert_proportion": 1,
        "key_dist": "zipfian",
        "value_length": 100
}
```
Output (run with a cache limit of 10GB and 2 threads): `[1657364785:642][1213812:0x7f3672c8b640], file:access.wt, WT_CURSOR.insert: [WT_VERB_DEFAULT][ERROR]: __wt_cursor_kv_not_set, 225: requires value be set: Invalid argument
Segmentation fault (core dumped)`
Running the same workload with one thread works fine.

Could this be due to the fact that the wrapper uses a shared `WT_CURSOR` although this is not thread-safe (https://source.wiredtiger.com/11.0.0/threads.html)?

**Comment by ashvardanian** [comment]
Thank you for your participation and for the feedback. You are exactly right, the `WT_CURSOR` is not thread-safe. We have fixed the issue in internal forks and will update the public version accordingly very soon.

**Comment by ashvardanian** [comment]
I also want to note that initialization can't be multithreaded with WiredTiger. Initialization can only work on top of an empty state. If one thread has already started filling a collection, others can't interfere. Alternatively, use "Batch Upserts".

**Comment by ashvardanian** [comment]
That issue was solved by our recent commit: https://github.com/unum-cloud/UCSB/commit/942765daffd2d68d3e26bfdec7b93a8fc1a8f20a
